name: Compilation of NSP
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  compilation_ubuntu:
    name: Compilation for Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install ocaml gfortran tcl8.6-dev tk8.6-dev tcl8.6 tk8.6
          sudo apt-get install libgtk-3-dev libgtksourceview-3.0-dev libvte-dev libtool libtool-bin
      - name: Checkout NSP
        uses: actions/checkout@v3
      - name: Compile NSP
        run: |
          ./autogen.sh
          ./configure
          make -j1
          sudo make install
